# creation rules are evaluated sequentially, the first match wins
creation_rules:
        # upon creation of a file that matches the pattern *dev.yaml,
        # KMS set A is used

        # PROD environment ------------------------------------------------------------------------------------------------------------- #
        - kms: "arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2"
          encrypted_regex: '^(secrets)$'
          path_regex: 'mukta-prod-.*\.yaml'

        # UAT environment ------------------------------------------------------------------------------------------------------------- #
        - kms: "arn:aws:kms:ap-south-1:218381940040:key/9a3b0835-7713-4925-8b3d-da7e421d28d2"
          encrypted_regex: '^(secrets)$'
          path_regex: 'mukta-uat-.*\.yaml'


